### ISSUE TITLE
URLError when download AppleWWDRCA.cer

### ISSUE THREAD

**Issue by chnbohwr** [grinich/mdmvendorsign#7]
```
Downloading WWDR intermediate certificate...Traceback (most recent call last):
  File "mdm_vendor_sign.py", line 162, in <module>
    mdm_vendor_sign()
  File "mdm_vendor_sign.py", line 129, in mdm_vendor_sign
    intermediate_cer = urllib2.urlopen(req).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>
```

**Comment by nathanaherne** [comment]
I am getting the same issue, though the link seems to work. If I find out what the problem is, I will come back to you BUT be aware that I am not a very good Python programmer so I might not find the problem.

**Comment by dleonard00** [comment]
vuid-com has a fix for this on their [fork](https://github.com/vuid-com/mdmvendorsign).
